apiVersion: v1
kind: ConfigMap
metadata:
  name: ea-config
data:
  config.yaml: |
    es_host: 127.0.0.1
    es_port: 9200
    es_password: "1234"

    rules_folder: /config/rules

    buffer_time:
        minutes: 15
        seconds: 30

    writeback_index: elastalert_status

    run_every:
        seconds: 30